### ISSUE TITLE
Checksum failure on stitch-0.1.0

### ISSUE THREAD

**Issue by taktoa** [C4K3/crates-ectype#1]
There is a checksum failure when downloading [stitch-0.1.0](https://crates.io/crates/stitch/0.1.0) that won't go away no matter what I do; I tried rerunning it a few times (in case it was a network issue) and I tried running with `--no-check-sums`. The only way I could get the mirroring to proceed was by deleting  the `index/st/it/` directory and running it with `--no-update-index`. It would be nice if `crates-ectype` was a little more fault-tolerant (i.e.: it didn't just quit when a single checksum fails).

**Comment by C4K3** [comment]
That's caused by an inconsistency in the index database, and has happened before https://github.com/rust-lang/crates.io/issues/1201

For my own use, I just add it to the hardcoded list of ignored crates, but you're right that's not a very resilient solution.

I think I'll have it just ignore crates with checksum mismatches (maybe print a warning, but definitely don't save the .crate with mismatched checksum,) and then add in an option to have it fail (current functionality.)
